---
replicaCount: 1

fullnameOverride: "trace-api-wrapper"

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false

# These values are the default, but if they are not in this file,
# the ingress' paths are not rendered by Helm.
# As the api-wrapper is deprecated as of 7/22 we'll just duplicate the config here.
edc:
  endpoints:
    # Default api for client communications
    default:
      port: "9191"
      path: /api
      ingress: true
    # Callback endpoint for EDC
    callback:
      port: "9192"
      path: /callback
      ingress: false

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls: true
  className: "nginx"
  hostname: trace-api-wrapper.int.demo.catena-x.net
  certManager:
    clusterIssuer: letsencrypt-prod

resources:
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 256Mi

##
## EDC & API-Wrapper configuration.properties
##
## For the EDC configuration consult the eclipse-dataspaceconnector documentation for further details: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector
##
configuration:
  properties: |-
    edc.api.control.auth.apikey.key=X-Api-Key
    edc.api.control.auth.apikey.value=<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
    # edc.core.retry.backoff.max=
    # edc.core.retry.backoff.min=
    # edc.core.retry.retries.max=
    # edc.core.system.health.check.liveness-period=
    # edc.core.system.health.check.readiness-period=
    # edc.core.system.health.check.startup-period=
    # edc.core.system.health.check.threadpool-size=
    # edc.fs.config=
    edc.hostname=trace-consumer-controlplane
    # edc.web.rest.cors.enabled=
    # edc.web.rest.cors.headers=
    # edc.web.rest.cors.methods=
    # edc.web.rest.cors.origins=
    # wrapper.auth.basic.user-x=password-x
    wrapper.consumer.edc.control.url=http://trace-consumer-controlplane:9999/api/controlplane/control
    wrapper.consumer.edc.datamanagement.url=http://trace-consumer-controlplane:8181/data
    wrapper.consumer.edc.apikey.name=X-Api-Key
    wrapper.consumer.edc.apikey.value=<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
    wrapper.callback.timeout=30
    wrapper.auth.basic.tracefoss=<path:traceability-foss/data/int/edc/api-wrapper#wrapper.auth.basic.tracefoss>
