management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: notifications@catena-x.net
    password: ${MAILSERVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true