management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
    mail:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
  server:
    port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_OAUTH2_CLIENT_ID}
            client-secret: ${KEYCLOAK_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
  config:
    import: swagger.yml
  mail:
    templates:
      path: mail-templates
    host: smtp.office365.com
    port: 587
    username: notifications@catena-x.net
    password: ${MAILSERVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: false
  bpnApi:
    connectionTimeoutMillis: 200
    readTimeoutMillis: 500
    maxIdleConnections: 10
    keepAliveDurationMinutes: 5

cache:
  bpn:
    name: "bpn-mappings"
    maximumSize: 500
    expireAfterWrite: 1d

cors:
  origins: >
    http://localhost:4200/,
    https://traceability-portal.dev.demo.catena-x.net/,
    https://traceability-portal.int.demo.catena-x.net/
