keycloak:
  auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
  realm: CX-Central
  resource: Cl10-CX-Part
  public-client: true

feign:
  bpnApi:
    url: "https://catenax-bpdm-dev.germanywestcentral.cloudapp.azure.com/"
