management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
  server:
    port: 8081

spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: notifications@catena-x.net
    password: ${MAILSERVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true