components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

swagger:
  operations:
    api.assets:
      summary: "Returns all assets"
      notes: "The results are paginated"
      authorizations: "#components/securitySchemes/bearerAuth"
    api.assets.sync:
      summary: "Synchronizes assets from IRS"
      authorizations: "#components/securitySchemes/bearerAuth"
    api.assets.assetId:
      summary: "Returns single asset by given assetId"
      params:
        assetId: "Unique ID of an asset"
      authorizations: "#components/securitySchemes/bearerAuth"
    api.assets.assetId.children.childId:
      summary: "Returns a single child of an asset by given assetId and childId"
      params:
        assetId: "Unique ID of an asset"
        childId: "Unique ID of a child asset"
      authorizations: "#components/securitySchemes/bearerAuth"
    api.dashboard:
      summary: "Returns dashboard related data"
      notes: "The endpoint can return limited data based on the user role"
      authorizations: "#components/securitySchemes/bearerAuth"
