image:
  tag: $ARGOCD_APP_REVISION

springprofile: int #will be set as int

nameOverride: "product-traceability-foss-pen-backend"
fullnameOverride: "product-traceability-foss-pen-backend"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP


  hosts:
    - host: "traceability-pen-portal.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "traceability-pen-portal.int.demo.catena-x.net"
      secretName: tls-secret

mailserver:
  host: "smtp.office365.com"
  port: "587"
  username: "notifications@catena-x.net"
  password: <path:traceability-foss/data/int#mailserverPassword>

datasource:
  url: jdbc:postgresql://product-traceability-foss-backend-postgresql:5432/trace
  username: trace
  password: <path:traceability-foss/data/pen/database#tracePassword>

oauth2:
  clientId: <path:traceability-foss/data/pen/keycloak/oauth2#clientId>
  clientSecret: <path:traceability-foss/data/pen/keycloak/oauth2#clientSecret>
  clientTokenUri: " https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
  jwkSetUri: " https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  resourceClient: "Cl17-CX-Part"

postgresql:
  enabled: true
  auth:
    postgresPassword: "<path:traceability-foss/data/pen/database#postgresPassword>"
    password: "<path:traceability-foss/data/pen/database#tracePassword>"
    database: "trace"
    username: "trace"

pgadmin4:
  enabled: false

irs:
  enabled: false

