image:
  tag: $ARGOCD_APP_REVISION

springprofile: int

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - host: "traceability.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "traceability.int.demo.catena-x.net"
      secretName: tls-secret

mailserver:
  host: "smtp.office365.com"
  port: "587"
  username: "notifications@catena-x.net"
  password: <path:traceability-foss/data/int#mailserverPassword>

datasource:
  url: jdbc:postgresql://tracex-backend-postgresql-hl:5432/trace
  username: trace
  password: <path:traceability-foss/data/int/database#tracePassword>

oauth2:
  clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
  clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
  clientTokenUri: "https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
  jwkSetUri: "https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  resourceClient: "Cl17-CX-Part"

postgresql:
  enabled: true
  fullnameOverride: "tracex-backend-postgresql"
  auth:
    postgresPassword: "<path:traceability-foss/data/int/database#postgresPassword>"
    password: "<path:traceability-foss/data/int/database#tracePassword>"
    database: "trace"
    username: "trace"

pgadmin4:
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: tracex-pgadmin4.int.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - tracex-pgadmin4.int.demo.catena-x.net
        secretName: tls-secret
  env:
    email: pgadmin4@trace.foss
    password: "<path:traceability-foss/data/int/database#pgadminPassword>"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# for IRS, but needs to be on the base level
global:
  enablePrometheus: false
  enableGrafana: false

irs-helm:
  enabled: true

  nameOverride: "tracex-irs"
  fullnameOverride: "tracex-irs"

  namespace: product-traceability-foss

  irsUrl: "https://tracex-irs.int.demo.catena-x.net"
  ingress:
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: "tracex-irs.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "tracex-irs.int.demo.catena-x.net"
        secretName: tls-secret

  digitalTwinRegistry:
    url: https://tracex-aas-registry.int.demo.catena-x.net
  semanticsHub:
    url: https://semantics.int.demo.catena-x.net/hub/api/v1
  bpdm:
    url: https://partners-pool.int.demo.catena-x.net
  minioUser: <path:traceability-foss/data/dev/minio#user>
  minioPassword: <path:traceability-foss/data/dev/minio#password>
  keycloak:
    oauth2:
      clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
      clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
      clientTokenUri: https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      jwkSetUri: https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

  aasWrapper:
    username: tracefoss
    password: <path:traceability-foss/data/int/edc/api-wrapper#wrapper.auth.basic.tracefoss>

  irs-minio:
    minioUser: <path:traceability-foss/data/int/minio#user>
    minioPassword: <path:traceability-foss/data/int/minio#password>

  irs-aaswrapper:
    edc:
      api:
        auth:
          key: <path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>

  postgresql:
    auth:
      postgresPassword: <path:traceability-foss/data/int/edc/database#password>
      password: <path:traceability-foss/data/dev/int/database#password>

  # Values for consumer edc-controlplane.
  edc-controlplane:
    ingresses:
      - enabled: true
        hostname: "tracex-consumer-controlplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        endpoints:
          - ids
          - data
        className: "nginx"
        tls:
          - hosts:
              - "tracex-consumer-controlplane.int.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.dataspaceconnector.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    edc:
      postgresql:
        password: <path:traceability-foss/data/int/edc/database#password>
      transfer:
        proxy:
          token:
            verifier:
              publickey:
                alias: token-signer-cert-int
            signer:
              privatekey:
                alias: token-signer-cert-key-int
      api:
        auth:
          key: <path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
      controlplane:
        url: "tracex-consumer-controlplane.int.demo.catena-x.net"
      dataplane:
        url: "tracex-consumer-dataplane.int.demo.catena-x.net"
    configuration:
      properties: |-
        edc.oauth.client.id=D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F:keyid:D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F
        edc.oauth.public.key.alias=daps-cert-int
        edc.oauth.private.key.alias=daps-cert-key-int
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token
        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/int/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss
        edc.data.encryption.keys.alias=edc-data-encryption-keys-alias
        edc.data.encryption.algorithm=AES

  # Values for consumer edc-dataplane.
  edc-dataplane:
    edc:
      api:
        auth:
          key: <path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>

    ingresses:
      - enabled: true
        hostname: "tracex-consumer-dataplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        endpoints:
          - public
        className: "nginx"
        tls:
          - hosts:
              - "tracex-consumer-dataplane.int.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.dataspaceconnector.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    configuration:
      properties: |-
        edc.oauth.client.id=D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F:keyid:D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F
        edc.oauth.public.key.alias=daps-cert-int
        edc.oauth.private.key.alias=daps-cert-key-int
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token
        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/int/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss
