spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    port: 3025
    username: notifications
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
