spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: "traceability-foss-integration-tests"
            client-secret: "integration-tests"
  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    port: 3025
    username: notifications
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  autoconfigure:
    exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration, org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration

keycloak:
  enabled: false
