spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    username: notifications@catena-x.net
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true