strategy:
  type: Recreate # the PVC cannot be connected to more than one pod

## Server definitions will be loaded at launch time. This allows connection
## information to be pre-loaded into the instance of pgAdmin4 in the container.
## Ref: https://www.pgadmin.org/docs/pgadmin4/latest/import_export_servers.html
##
serverDefinitions:
  enabled: true

  servers:
    firstServer:
      Name: "Traceability PostgreSQL"
      Group: "Servers"
      Port: 5432
      Username: "postgres"
      Host: "traceability-database-postgresql-hl"
      SSLMode: "required"
      MaintenanceDB: "postgres"

networkPolicy:
  enabled: false

## Ingress
## Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  ingressClassName: "nginx"
  hosts:
    - host: trace-pgadmin4.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - trace-pgadmin4.dev.demo.catena-x.net
      # Default secret for certificate creation already provided to your namespace
      secretName: trace-pgadmin4-tls-secret

env:
  email: pgadmin4@trace.foss
  password: <path:traceability-foss/data/dev/database#pgadminPassword>

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
