create table shell_descriptor
(
	id                  int8 generated by default as identity,
	created             timestamptz not null,
	updated             timestamptz not null,
	shell_descriptor_id text not null,
	global_asset_id     text not null
);
