create table registry_lookup_metrics (
    id int8 generated by default as identity,
    bpn varchar(255),
    status varchar(255),
    start_date timestamp,
    end_date timestamp,
	success_shell_descriptors_fetch_count int4,
	failed_shell_descriptors_fetch_count int4
);
