---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-wrapper.fullname" . }}
  labels:
    {{- include "api-wrapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.edc.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.edc.endpoints.callback.port }}
      targetPort: callback
      protocol: TCP
      name: callback
  selector:
    {{- include "api-wrapper.selectorLabels" . | nindent 4 }}
