{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "product-traceability-foss-backend.namespace" . }}
  name: {{ include "product-traceability-foss-backend.serviceAccountName" . }}
  labels:
    {{- include "product-traceability-foss-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
