name: "Eclipse DASH IP Check"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Gradle IP dependency check with eclipse dash tool
        run: ./.github/scripts/eclipse_dash.sh
        shell: bash

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: 'DASH_SUMMARY'


