name: "Eclipse DASH IP Check"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

env:
  JAVA_VERSION: 17


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Gradle check dependencies with eclipse dash tool
        run: |
          ./gradlew dependencies | grep -Poh "(?<=\s)[\w\.-]+:[\w\.-]+:[^:\s]+" | grep -v "^org\.eclipse" | sort | uniq > DEPENDENCIES
          java -jar org.eclipse.dash.licenses-0.0.1-20221105.055038-599.jar DEPENDENCIES -project automotive.tractusx -summary DASH_SUMMARY
          grep "restricted" DASH_SUMMARY | if test $(wc -l) -gt 0; then exit 1; fi
        shell: bash
      - name: upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: 'DASH_SUMMARY'


