name: "Integration test"

on:
  push:

jobs:
  Integration-test:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run integration tests
        run: ./gradlew integrationTest

      - name: Publish integration test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          junit_files: "build/test-results/test/*.xml"
          check_name: "Integration Test Results"
