---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-wrapper.fullname" . }}-configmap
  labels:
    {{- include "api-wrapper.labels" . | nindent 4 }}
data:
  dataspaceconnector-configuration.properties: |-
    web.http.default.port={{ .Values.edc.endpoints.default.port }}
    web.http.default.path={{ .Values.edc.endpoints.default.path }}
    web.http.callback.port={{ .Values.edc.endpoints.callback.port }}
    web.http.callback.path={{ .Values.edc.endpoints.callback.path }}
    {{- .Values.configuration.properties | nindent 4 }}
