{{- if eq (.Values.networkPolicy.enabled | toString) "true"  }}
{{- $fullName := include "api-wrapper.fullname" . }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "api-wrapper.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "api-wrapper.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    {{- toYaml .Values.networkPolicy.from | nindent 4}}
    ports:
      - protocol: TCP
        port: {{ .Values.edc.endpoints.default.port }}
      - protocol: TCP
        port: {{ .Values.edc.endpoints.callback.port }}
  policyTypes:
  - Ingress
{{- end }}

