{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-wrapper.fullname" . }}-secret
  labels:
    {{- include "api-wrapper.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}

